# fly.toml app configuration file generated for bugtracker-backend-gilalvarado on 2026-06-30T11:39:18-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bugtracker-backend-gilalvarado'
primary_region = 'ord'

[build]

[mounts]
  source="bugtracker_data"
  destination="/data"

[env]
  DB_PATH = "/data/bugs.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
